const actionTypes ={
    /* PRODUCT ACTIONS START */
    PRODUCT_LIST_REQUEST: 'PRODUCT_LIST_REQUEST',
    PRODUCT_LIST_SUCCESS: 'PRODUCT_LIST_SUCCESS',
    PRODUCT_LIST_FAIL: 'PRODUCT_LIST_FAIL',
    /* PRODUCT ACTIONS END */
    USER_STARTED: 'USER_STARTED',
    USER_SUCCESS: 'USER_SUCCESS',
    USER_FAIL:  'USER_FAIL',
    
    REGISTER_USER_REQUEST: 'REGISTER_USER_REQUEST',
    REGISTER_USER_STARTED: 'REGISTER_USER_STARTED',
    REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
    REGISTER_USER_FAIL: 'REGISTER_USER_FAIL',
    REGISTER_USER_LOGOUT: 'REGISTER_USER_LOGOUT',
};

export default actionTypes;